const std = @import("std");

pub const cf = @import("core_foundation.zig");
pub const cg = @import("core_graphics.zig");
pub const ct = @import("core_text.zig");
pub const objc = @import("objc.zig");
pub const media_remote = @import("media_remote.zig");

// CoreFoundation re-exports
pub const Ref = cf.Ref;
pub const DictionaryCallbacks = cf.DictionaryCallbacks;
pub extern "c" var kCFTypeDictionaryKeyCallBacks: DictionaryCallbacks;
pub extern "c" var kCFTypeDictionaryValueCallBacks: DictionaryCallbacks;
pub const CFRelease = cf.CFRelease;
pub const CFRetain = cf.CFRetain;
pub const CFStringCreateWithBytes = cf.CFStringCreateWithBytes;
pub const CFStringGetCString = cf.CFStringGetCString;
pub const CFStringGetLength = cf.CFStringGetLength;
pub const CFGetTypeID = cf.CFGetTypeID;
pub const CFStringGetTypeID = cf.CFStringGetTypeID;
pub const CFDictionaryGetValue = cf.CFDictionaryGetValue;
pub const CFArrayGetCount = cf.CFArrayGetCount;
pub const CFArrayGetValueAtIndex = cf.CFArrayGetValueAtIndex;
pub const CFNumberGetValue = cf.CFNumberGetValue;
pub const CFDictionaryCreate = cf.CFDictionaryCreate;
pub const CFAttributedStringCreate = cf.CFAttributedStringCreate;
pub const CFURLCreateFromFileSystemRepresentation = cf.CFURLCreateFromFileSystemRepresentation;
pub const CFNotificationCenterGetDistributedCenter = cf.CFNotificationCenterGetDistributedCenter;
pub const CFNotificationCenterAddObserver = cf.CFNotificationCenterAddObserver;
pub const string = cf.string;

// CoreGraphics re-exports
pub const Point = cg.Point;
pub const Size = cg.Size;
pub const Rect = cg.Rect;
pub const rect = cg.rect;
pub extern "c" var kCGWindowBounds: Ref;
pub extern "c" var kCGWindowName: Ref;
pub extern "c" var kCGWindowOwnerName: Ref;
pub extern "c" var kCGWindowLayer: Ref;
pub extern "c" var kCGWindowNumber: Ref;
pub const CGWindowListCopyWindowInfo = cg.CGWindowListCopyWindowInfo;
pub const CGRectMakeWithDictionaryRepresentation = cg.CGRectMakeWithDictionaryRepresentation;
pub const CGColorSpaceCreateDeviceRGB = cg.CGColorSpaceCreateDeviceRGB;
pub const CGColorSpaceRelease = cg.CGColorSpaceRelease;
pub const CGColorCreate = cg.CGColorCreate;
pub const CGColorRelease = cg.CGColorRelease;
pub const CGBitmapContextCreate = cg.CGBitmapContextCreate;
pub const CGBitmapContextGetData = cg.CGBitmapContextGetData;
pub const CGBitmapContextCreateImage = cg.CGBitmapContextCreateImage;
pub const CGContextRelease = cg.CGContextRelease;
pub const CGContextTranslateCTM = cg.CGContextTranslateCTM;
pub const CGContextScaleCTM = cg.CGContextScaleCTM;
pub const CGContextRotateCTM = cg.CGContextRotateCTM;
pub const CGContextSetAlpha = cg.CGContextSetAlpha;
pub const CGContextSetBlendMode = cg.CGContextSetBlendMode;
pub const CGContextBeginTransparencyLayer = cg.CGContextBeginTransparencyLayer;
pub const CGContextEndTransparencyLayer = cg.CGContextEndTransparencyLayer;
pub const CGContextSetRGBFillColor = cg.CGContextSetRGBFillColor;
pub const CGContextSetRGBStrokeColor = cg.CGContextSetRGBStrokeColor;
pub const CGContextSetLineJoin = cg.CGContextSetLineJoin;
pub const CGContextSetLineWidth = cg.CGContextSetLineWidth;
pub const CGContextSetShouldAntialias = cg.CGContextSetShouldAntialias;
pub const CGContextSetTextPosition = cg.CGContextSetTextPosition;
pub const CGContextClipToRect = cg.CGContextClipToRect;
pub const CGContextClipToMask = cg.CGContextClipToMask;
pub const CGContextFillRect = cg.CGContextFillRect;
pub const CGContextDrawImage = cg.CGContextDrawImage;
pub const CGContextSaveGState = cg.CGContextSaveGState;
pub const CGContextRestoreGState = cg.CGContextRestoreGState;
pub const CGContextBeginPath = cg.CGContextBeginPath;
pub const CGContextMoveToPoint = cg.CGContextMoveToPoint;
pub const CGContextAddLineToPoint = cg.CGContextAddLineToPoint;
pub const CGContextClosePath = cg.CGContextClosePath;
pub const CGContextDrawPath = cg.CGContextDrawPath;
pub const CGContextAddPath = cg.CGContextAddPath;
pub const CGContextClip = cg.CGContextClip;
pub const CGContextFillPath = cg.CGContextFillPath;
pub const CGPathCreateWithRoundedRect = cg.CGPathCreateWithRoundedRect;
pub const CGPathRelease = cg.CGPathRelease;
pub const CGImageRetain = cg.CGImageRetain;
pub const CGImageRelease = cg.CGImageRelease;
pub const CGImageSourceCreateWithURL = cg.CGImageSourceCreateWithURL;
pub const CGImageSourceCreateImageAtIndex = cg.CGImageSourceCreateImageAtIndex;
pub const kCGImageAlphaPremultipliedLast = cg.kCGImageAlphaPremultipliedLast;
pub const kCGBitmapByteOrder32Big = cg.kCGBitmapByteOrder32Big;
pub const kCGBlendModePlusLighter = cg.kCGBlendModePlusLighter;
pub const kCGPathFillStroke = cg.kCGPathFillStroke;
pub const kCGLineJoinRound = cg.kCGLineJoinRound;

// CoreText re-exports
pub extern "c" var kCTFontAttributeName: Ref;
pub extern "c" var kCTForegroundColorAttributeName: Ref;
pub const CTFontCreateUIFontForLanguage = ct.CTFontCreateUIFontForLanguage;
pub const CTLineCreateWithAttributedString = ct.CTLineCreateWithAttributedString;
pub const CTLineGetTypographicBounds = ct.CTLineGetTypographicBounds;
pub const CTLineCreateTruncatedLine = ct.CTLineCreateTruncatedLine;
pub const CTLineDraw = ct.CTLineDraw;
pub const kCTFontUIFontSystem = ct.kCTFontUIFontSystem;
pub const kCTFontUIFontEmphasizedSystem = ct.kCTFontUIFontEmphasizedSystem;
pub const kCTLineTruncationEnd = ct.kCTLineTruncationEnd;

// Objective-C runtime re-exports
pub const objc_getClass = objc.objc_getClass;
pub const sel_registerName = objc.sel_registerName;
pub const objc_msgSend = objc.objc_msgSend;
pub const objc_allocateClassPair = objc.objc_allocateClassPair;
pub const objc_registerClassPair = objc.objc_registerClassPair;
pub const class_addMethod = objc.class_addMethod;
pub const dispatch_async_f = objc.dispatch_async_f;
pub const dispatch_get_main_queue = objc.dispatch_get_main_queue;
pub const send0 = objc.send0;
pub const send1 = objc.send1;
pub const send2 = objc.send2;
pub const send3 = objc.send3;
pub const send4 = objc.send4;
